// The **release** build (R8 minification + dependency collection) needs more Gradle heap than the 2 GB Expo
// defaults to, or `:app:collectReleaseDependencies` dies with "Java heap space". `android/gradle.properties` is
// gitignored and regenerated by every `prebuild --clean`, so the bump has to live here to survive — otherwise
// the next release build OOMs and the reason is a mystery.
const { withGradleProperties } = require("@expo/config-plugins");

module.exports = function withReleaseHeap(config) {
  return withGradleProperties(config, (cfg) => {
    const set = (key, value) => {
      const existing = cfg.modResults.find((i) => i.type === "property" && i.key === key);
      if (existing) existing.value = value;
      else cfg.modResults.push({ type: "property", key, value });
    };
    set("org.gradle.jvmargs", "-Xmx6144m -XX:MaxMetaspaceSize=1024m");
    return cfg;
  });
};
