// Bake the policy documents into the bundle.
//
// The canonical text lives in `reference/*.md` (repo root) — a lawyer-shaped document, edited as prose. The
// app cannot read a repo file at runtime, so it ships a generated copy. That opens a gap: the text the user
// **agreed to** and the text we **keep on file** could drift apart, and consent to a document we no longer
// have is not consent at all.
//
// So: this script regenerates the copy, and `legal.generated.test.ts` re-derives it and fails the build if it
// differs. Editing a policy means running `npm run legal:sync` — you cannot forget, the test won't let you.
//
//   node scripts/sync-legal.js        (npm run legal:sync)

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..", "..");
const OUT = path.resolve(__dirname, "..", "src", "content", "legal.generated.ts");

/** The three documents, in the order they are shown at signup. `required` = the user cannot sign up without it. */
const DOCS = [
  {
    key: "terms",
    file: "reference/terms-of-service.md",
    title: "이용약관",
    // The consent line at signup. It carries the 만 14세 requirement the terms themselves impose (제4조 2항 1호),
    // so the age check does not need a row of its own.
    consent: "(필수) 만 14세 이상이며, 이용약관에 동의합니다",
    required: true,
  },
  {
    key: "privacy",
    file: "reference/privacy-policy.md",
    title: "개인정보처리방침",
    consent: "(필수) 개인정보 수집·이용에 동의합니다",
    required: true,
  },
  {
    key: "location",
    file: "reference/locate-policy.md",
    title: "위치기반서비스 이용약관",
    // Optional **on purpose**: the app collects no location today, and the feature it is for (spotting that you
    // actually walked into the gym — privacy-policy §8) does not exist yet. Gating signup on a permission we
    // never ask for would be extracting a consent we have no use for.
    consent: "(선택) 위치기반서비스 이용약관에 동의합니다",
    required: false,
  },
];

/**
 * Bump this when a policy's **meaning** changes. It is stamped on the user's consent record, and a record
 * stamped with an older version is what re-asks them — so a silent edit + no bump means we would go on
 * claiming they agreed to words they never saw.
 */
const LEGAL_VERSION = "2026-07-14";

const read = (rel) => {
  const p = path.join(ROOT, rel);
  const text = fs.readFileSync(p, "utf8").replace(/\r\n/g, "\n").trimEnd();
  if (!text) throw new Error(`${rel} is empty`);
  return text;
};

function generate() {
  const entries = DOCS.map((d) => {
    const body = read(d.file);
    return `  ${d.key}: {
    key: "${d.key}",
    title: ${JSON.stringify(d.title)},
    source: ${JSON.stringify(d.file)},
    consent: ${JSON.stringify(d.consent)},
    required: ${d.required},
    body: ${JSON.stringify(body)},
  },`;
  }).join("\n");

  return `// GENERATED by scripts/sync-legal.js — DO NOT EDIT.
// Edit the source documents in \`reference/\` and run \`npm run legal:sync\`.
// (legal.generated.test.ts fails if this file and \`reference/\` disagree.)

export type LegalKey = "terms" | "privacy" | "location";

export interface LegalDoc {
  key: LegalKey;
  /** What it is called on screen. */
  title: string;
  /** Where the canonical text lives. */
  source: string;
  /** The single line the user ticks at signup. */
  consent: string;
  /** Signup is blocked until every required document is agreed to. */
  required: boolean;
  /** The full text, verbatim. */
  body: string;
}

/** Bumped when a policy's meaning changes — that is what re-asks the user for consent. */
export const LEGAL_VERSION = ${JSON.stringify(LEGAL_VERSION)};

export const LEGAL_DOCS: Record<LegalKey, LegalDoc> = {
${entries}
};

/** Signup order. */
export const LEGAL_ORDER: LegalKey[] = [${DOCS.map((d) => `"${d.key}"`).join(", ")}];
`;
}

// **Writing only happens when this is RUN, never when it is imported.** The drift test imports `generate()`
// to compare against what is on disk — if importing also *wrote* to disk, the test would repair the drift it
// exists to catch and then pass, every time, no matter what. A guard that fixes the thing before checking it
// is not a guard.
if (require.main === module) {
  const next = generate();
  const prev = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (prev === next) {
    console.log("legal: already in sync");
  } else {
    fs.mkdirSync(path.dirname(OUT), { recursive: true });
    fs.writeFileSync(OUT, next);
    console.log(`legal: wrote ${path.relative(process.cwd(), OUT)}`);
  }
}

module.exports = { generate, OUT, DOCS, LEGAL_VERSION };
